[tool.black]
line-length = 80
include = '\.pyi?$'

[project]
name = "forest_gen"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.0.0",
    "opensimplex==0.4.5.1",
    "trimesh==4.6.6",
    "scipy>=1.0.0",
    "neuroforgelab @ git+ssh://git@github.com/GrafCzterech/NeuroForgeLab.git@main",
]

[tool.setuptools]
packages = ["forest_gen", "forest_gen.heightmap", "forest_gen.asset_dist"]
package-dir = { "" = "src" }

[project.optional-dependencies]
dev = ["black"]
test = ["unittest"]
vis = ["matplotlib"]

[project.urls]
Repository = "https://github.com/GrafCzterech/forest-gen"
